<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <OsuLazerCurrentPath Condition="'$(OsuLazerCurrentPath)' == ''">$(LocalAppData)\osulazer\current</OsuLazerCurrentPath>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\LazerReplayCompare\LazerReplayCompare.csproj" />
    <ProjectReference Include="..\RawScoreBatchAnalyzer\RawScoreBatchAnalyzer.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="osu.Game">
      <HintPath>$(OsuLazerCurrentPath)\osu.Game.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
